### ISSUE TITLE
attempting to hard uninstall and install to get working again

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/readynas-sickchill#10]
in attempt to fix i copied my app-config folder to a different location.  then removed sickrage app.  and attempted to install `sudo dpkg -i sickrage_2018.02.17-ml0_all.deb` which should work.

```
[[0;1;32m●[[0m fvapp-sickrage.service - Service for sickrage app
   Loaded: loaded (/lib/systemd/system/fvapp-sickrage.service; enabled; vendor preset: enabled)
   Active: [[0;1;32mactive (running)[[0m since Wed 2018-11-07 18:49:23 MST; 2s ago
 Main PID: 4456 (python)
   CGroup: /system.slice/fvapp-sickrage.service
           └─4456 /usr/bin/python /apps/sickrage/SickBeard.py --nolaunch --datadir=/apps/sickrage/app-config --config=/apps/sickrage/app
-config/config.ini --port=6765

Nov 07 18:49:23 AustinReadyNAS systemd[1]: Started Service for sickrage app.
```

but i am getting:
```
192.168.1.133 didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by Mhynlo** [comment]
It looks like you are attempting to use the SickRage app.
I have created the newer version of SickChill app that uses all of the SickChill resources:
https://github.com/SickChill/readynas-sickchill/releases/tag/2018.11.07-ml0

(You should have better luck with this version.)

Tip: You can use `apt` for installing the debian packages to help install the dependencies.
```apt install ./sickrage_2018.11.07-ml0_all.deb```

**Comment by theskillwithin** [comment]
Thank you!!!
