### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by horganhoozen** [SickChill/readynas-sickchill#12]
Installed the latest version 2018.11.07-ml10_all.deb using apt install method.
Made sure sickrage was turned off first. Launched sickchill and received ERR_CONNECTION_REFUSED in browser under new port 6766.
Below is ssh output
```
● fvapp-sickchill.service - Service for sickchill app
   Loaded: loaded (/lib/systemd/system/fvapp-sickchill.service; enabled; vendor
preset: enabled)
   Active: active (running) since Thu 2018-11-15 16:47:35 EST; 1s ago
 Main PID: 5428 (python)
   CGroup: /system.slice/fvapp-sickchill.service
           └─5428 /usr/bin/python /apps/sickchill/SickBeard.py --nolaunch --data
dir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --
port=6766

Nov 15 16:47:35 MattFlix systemd[1]: Started Service for sickchill app.
```

please advise

**Comment by WebSpider** [comment]
Please add debug logging inline or as a gist.

**Comment by horganhoozen** [comment]
> Please add debug logging inline or as a gist.

I'm sorry, how do I get that?

**Comment by horganhoozen** [comment]
I am seeing this in the SSH console

```
Nov 15 17:07:03 MattFlix python[9327]: Config file must be writeable: /apps/sick
chill/app-config/config.ini
```

**Comment by horganhoozen** [comment]
Just wanted to let you know that the issue is resolved. I don't know why it wasn't working before but I just rebooted my ReadyNAS unit and now it's working. 

Thank you for this release!
