### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vlastaw** [SickChill/readynas-sickchill#13]
Hi, I am using Sickrage. Tried to install SickChill (all your packages from GitHub and Readynas app store), but none of these works. It returns 404, I'd guess: This website could not be found. Error Code: INET_E_RESOURCE_NOT_FOUND
Thanks for any suggestions.

**Comment by Mhynlo** [comment]
Are you still having this issue?
I haven't encountered anything, but I can build based on the latest build to see if that may help with any problems you might be experiencing.

**Comment by christiaanw1** [comment]
Good Day. I have a readynas and wantto use sickchill as my old outdated sickrage isn't finding episodes anymore. I also installed the sickchill package from the store but gives me the same error as vlastaw is getting. I'm a real noob when it gets to the programming stuff. Please help

**Comment by igiddyuup** [comment]
I'm having issues with this install as well.   It installs - but you cannot access the website for it http://readynas:6766 - just says the site cannot be reached. I uninstalled it, reinstalled it, updated my readynas, rebooted my readynas, nothing worked.

I'm running Readynas 204, os 6.10.1 (just updated after it didn't work on 6.9.x).  I do still have a copy of sickrage installed, 2018.02.17-ml0, and it's working fine still.  I just don't update it and it works.

**Comment by miigotu** [comment]
https://github.com/SickChill/readynas-sickchill/releases
