### ISSUE TITLE
randomly unknown current version number

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/readynas-sickchill#14]
had this installed for many months, updates have worked. but now I look and see error:

```
Unknown current version number: If you've never used the SickChill upgrade system before then current version is not set. — Update Now
```

**Comment by inversedrivenundefined** [comment]
I'm having the same problem. There hasn't been an commit since January 6th so I'm thinking it was the last update that did us in.

**Comment by inversedrivenundefined** [comment]
Look like the error is cleared up in the latest commit

**Comment by WebSpider** [comment]
@theskillwithin for you as well? If not, feel free to reopen
