### ISSUE TITLE
How to update via CLI

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/readynas-sickchill#17]
I noticed there is not .git file here, to my knowledge in sickchill if you want to update without opening the app you just do a `git pull`.

this is not usually a problem because the update functionality once u launch the app and view in browser works perfectly fine.

however a recent update broke sickchill for me, and i want to be able to update via cli to patch next time they put update out, since opening the app wont work until patch

**Comment by miigotu** [comment]
I would personally purge the package and reinstall it on there, because right now there are issues with residual files causing issues. Just make sure your config, db, and media are all outside of the install dir
