### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/readynas-sickchill#18]
are there plans for a python3 ready package

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/pull/6572
https://github.com/SickChill/SickChill/pull/6615

Once that is done all the dependant packages will start being worked on to use the new code.

**Comment by miigotu** [comment]
Those PR were just the first. You can follow the progress here: https://github.com/SickChill/SickChill/issues/6545

**Comment by theskillwithin** [comment]
Nice!

**Comment by theskillwithin** [comment]
@miigotu looks like it might be ready?

**Comment by miigotu** [comment]
Sure, but you have to get python3.6+ somehow.

**Comment by theskillwithin** [comment]
idk why but it automatically reverted `fvapp-sickchill.service` even tho i didn't run the install binary.
