### ISSUE TITLE
Cannot Update Sickchill on ReadyNas

### ISSUE THREAD

**Issue by christiaanw1** [SickChill/readynas-sickchill#20]
Cannot Run the update on sickchill. When I do It doesn't want to restart again and needs to be re-installed.

ReadyNas IOS: 6.10.4

**Comment by theskillwithin** [comment]
ya i experience this as well

**Comment by miigotu** [comment]
The readynas package has not been updated for the python3 version of SC yet. You need python3.6+ installed and then it should update I think. You will also need to edit `fvapp-sickchill.service` and change the line:
```---
ExecStart=/usr/bin/python /apps/sickchill/SickBeard.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766
```
to
```+++
ExecStart=/usr/bin/python3 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766

**Comment by gromitt42** [comment]
As an FYI I needed to use the below code in my `fvapp-sickchill.service`. I'm unsure if I messed up with my python install. 

`ExecStart=/usr/bin/python3 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766`

This and running `/usr/local/bin/python3.6 /apps/sickchill/SickChill.py` in SSH as root seemed allowed me to finally get Sickchill working after updating my install of version `sickchill_2020.05.12-ml0_all.deb`

**Comment by miigotu** [comment]
> As an FYI I needed to use the below code in my `fvapp-sickchill.service`. I'm unsure if I messed up with my python install as I needed to point to the USR/LOCAL/BIN folder
> 
> `ExecStart=/usr/local/bin/python3.6 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --`
> 
> This allowed me to finally get Sickchill working after updating my install of version `sickchill_2020.05.12-ml0_all.deb`
> 
You should have installed the 2021 release
https://www.github.com/SickChill/readynas-sickchill/tree/master/rn-files%2Ffvapp-sickchill.service

**Comment by gromitt42** [comment]
Thanks but the latest version wouldn't install for me. It just crashes.

**Comment by miigotu** [comment]
@gromitt42 I pushed a new version a bit ago: https://github.com/SickChill/readynas-sickchill/releases/tag/2021.03.09
