### ISSUE TITLE
Installer says need python >= 3.6 even tho I am on python 3.9

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/readynas-sickchill#22]
```
➜  sudo dpkg -i sickchill_2021.02.24_all.deb
(Reading database ... 64951 files and directories currently installed.)
Preparing to unpack sickchill_2021.02.24_all.deb ...
/usr/local/bin/python3.9
Unpacking sickchill (2021.02.24) over (2021.02.24) ...
dpkg: dependency problems prevent configuration of sickchill:
 sickchill depends on python3 (>= 3.6); however:
  Version of python3 on system is 3.4.2-2.

dpkg: error processing package sickchill (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 sickchill
➜  python3 --version
Python 3.9.0
```

**Comment by miigotu** [comment]
You installed 3.9 locally, rather than building a deb.

The final command of your source build for python should be `sudo checkinstall altinstall`, so that apt/dpkg know you have it installed.

Installing as a deb rather than a source makes it much easier to uninstall in the future.

**Comment by theskillwithin** [comment]
following this again which I had to do last time https://forums.sickrage.ca/t/how-to-install-on-readynas-and-python-3-6-9/275   (except doing with 3.9)

and https://stackoverflow.com/questions/44600424/how-to-install-python-3-x-version-in-usr-bin
adding --prefix=/usr flag to configure

takes a long time so i hope it works

**Comment by theskillwithin** [comment]
```
➜  sudo checkinstall altinstall
sudo: checkinstall: command not found
```

**Comment by theskillwithin** [comment]
```
➜  Documents sudo dpkg -i sickchill_2021.02.24_all.deb
Selecting previously unselected package sickchill.
(Reading database ... 53919 files and directories currently installed.)
Preparing to unpack sickchill_2021.02.24_all.deb ...
/usr/local/bin/python3.9
Unpacking sickchill (2021.02.24) ...
dpkg: dependency problems prevent configuration of sickchill:
 sickchill depends on python3 (>= 3.6); however:
  Version of python3 on system is 3.4.2-2.

dpkg: error processing package sickchill (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 sickchill
```

```
➜  which python3
/usr/local/bin/python3
➜  python3 --version
Python 3.9.0
➜  Documents
```

sigh readynas makes everything hard

**Comment by theskillwithin** [comment]
I was able to apt install checkinstall only after deleting the Python folder i wget'ed into ~

following this now https://linuxize.com/post/how-to-install-python-3-9-on-debian-10/

**Comment by theskillwithin** [comment]
Still not working, getting same error

**Comment by theskillwithin** [comment]
@miigotu  So I finally go it working I think but I had to use force flag
`sudo dpkg -i --force all sickchill_2021.02.24_all.deb`

and then `nano /etc/systemd/system/multi-user.target.wants/fvapp-sickchill.service` and tell it to use python3.9 and to point to sickchill

**Comment by miigotu** [comment]
You didn't need to touch the service file, and you only had to force install of python because you already had a python installed locally.
