### ISSUE TITLE
cannot install on readynas 6.10.5

### ISSUE THREAD

**Issue by CQuillinan** [SickChill/readynas-sickchill#26]
### Before submitting your issue:
Branch/Commit:sickchill_2018.11.07-ml0
OS:6.10.5
Browser:Chrome
What you did:
 I had version sickchill_2018.11.07-ml0_all.deb installed, i have tired updating to the latest available on https://github.com/SickChill/readynas-sickchill/releases/tag/2021.03.09

which is "sickchill_2021.03.09_all.deb" the install fails and corrupts the older app, to fix this I have to reinstall v 2018.11.07.  I then restore and its working fine again. 

i have tried uninstall this, and removed it and tired installing latest release and same issue, doesnt work.. 

I also tired this same process with older release and get same issues sickchill_2021.03.09_all.deb.

however what does work is the 2020 version. sickchill_2020.05.12-ml0_all.deb. if I uninstall the 2018 i can update to this. 

can you please help me with 2021 version? I will stay with 2018 version for now. 

I have 2 readynas and tried on both and same. I have ReadyNas 104 and ReadyNas 716 with same issues. 

all help is appreciated 

What happened: corrupts the install does upgrade have to reinstall old version and restore DB
What you expected:upgrade successful
Logs:
```
PASTE LOGS HERE
[System_log-CQRNAS-20211001-200438.zip](https://github.com/SickChill/readynas-sickchill/files/7269557/System_log-CQRNAS-20211001-200438.zip)
```

**Comment by CQuillinan** [comment]
yes i did and there seems to be something similar but resolution appears to be install newer version which doesnt work for me as above

**Comment by sharmyfrancis** [comment]
Hi.

2021.03.09 needs python 3.6 or later. Can you confirm that you have updated Python?

A good starting point is here: [https://github.com/SickChill/SickChill/wiki/ReadyNAS](url)

"Backup SickChill settings

Install Python 3.6.9

apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev libgdbm-dev libnss3-dev libssl-dev openssl
cd /root
wget http://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz
tar zxf Python-3.6.9.tgz
cd Python-3.6.9
./configure --enable-loadable-sqlite-extensions --enable-optimizations
make
make altinstall
Update SickChill Test new SickChill

/usr/local/bin/python3.6 /<YourSickChillLocation>/SickChill.py
Update your sickchill.service to use python3.6

For what it is worth, 2021.03.09 working perfectly on my 626X and Pro4 both running 6.10.5 Hotfix 1.'
