### ISSUE TITLE
Wrong logo

### ISSUE THREAD

**Issue by miigotu** [SickChill/readynas-sickchill#8]
I'm not sure if this effects the installed package, but the logo in the readme is wrong. Possibly could use:
![SC](https://github.com/SickChill/SickChill/raw/master/gui/slick/images/sickchill-sc.png)
or 
![logo](https://github.com/SickChill/SickChill/raw/master/gui/slick/images/sickchill.png)

**Comment by Mhynlo** [comment]
This has been done.
I will now post the app that includes the newer logo.
